modLoader="javafml"
loaderVersion="[37,)"
license="Order Of Obsidian"

[[mods]]
modId="orderofobsidian"
version="0.0.2"
displayName="OrderofObsidian"
credits="texture: Klaivert, Metalex, Model: Klaivert Code:Klaivert, Metalex"
displayURL="https://www.curseforge.com/minecraft/mc-mods/order-of-obsidian"
logoFile="logo.png"
authors="Klaivert,Metalex"

[[dependencies.orderofobsidian]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




