modLoader="javafml"
loaderVersion="[37,)"
license="Order Of Obsidian"

[[mods]]
modId="orderofobsidian"
version="0.0.2"
displayName="OrderofObsidian"
credits="texture: Klaivert, Métalex, Model: Klaivert Code:Klaivert, Métalex"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Klaivert,Métalex"

[[dependencies.orderofobsidian]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




